version: '3.3'

services:
  client:
    restart: always
    ports:
      - $PORT_CLIENT:3000
    build: .
    stdin_open: true
    tty: true
    command: yarn start
    depends_on:
      - web
    environment:
      NODE_ENV: development
      REACT_APP_URL_API: $URL_API
      REACT_APP_CONTACT_LINK: $CONTACT_LINK
      REACT_APP_MESSAGE_API: $URL_MESSAGE_API
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - .:/usr/src

  db:
    restart: always
    image: postgres

  web:
    image: kjgoodwins/foundation
    environment:
      - DATA=postgres://postgres:postgres@db
      - PASSWORD
      - PORT=3000
      - RAILS_ENV=development
    ports:
      - $PORT_API:3000
    volumes:
      - ./db:/foundation/db
      - ./models:/foundation/app/models
    depends_on:
      - db
    restart: always
