version: '3.3'

services:
  client:
    restart: on-failure
    ports:
      - $PORT_CLIENT:3000
    build: .
    stdin_open: true
    tty: true
    command: yarn start
    environment:
      NODE_ENV: development
      REACT_APP_URL_API: $URL_API
      REACT_APP_CONTACT_LINK: $CONTACT_LINK
      REACT_APP_MESSAGE_API: $URL_MESSAGE_API
      REACT_APP_LANGUAGE: $LANGUAGE
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - .:/usr/src

  db:
    restart: always
    image: postgres

  web:
    image: uwcirg/tb-foundation:$API_DOCKER_TAG
    environment:
      - DATA=postgres://postgres:postgres@db
      - PASSWORD
      - PORT=3000
      - RAILS_ENV=$ENVIRONMENT
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
      - URL_API=$URL_API
      - URL_CORS=$URL_CORS
      - WA_KEY=$WA_KEY
      - WA_SID=$WA_SID
    ports:
      - $PORT_API:3000
    depends_on:
      - db
    restart: always
    volumes:
      - source: user-documents
        target: /ruby/backend/upload/
        type: volume

  mongo:
    expose:
      - "27017"
    container_name: mongo
    image: "mongo"
    restart: always

  message:
    container_name: "message"
    depends_on:
      - mongo
    image: kjgoodwins/message
    ports:
      - "$PORT_MESSAGE:5002"
    environment:
      PORT: "5002"
      MDPORT: "mongo:27017"
      NAME: "message"
    restart: always

volumes:
    user-documents: {}
